version: v1.5.0.{build}

environment:
  NSIS_ROOT: C:\nsis

install:
  - appveyor DownloadFile "http://sunet.dl.sourceforge.net/project/nsis/NSIS 2/2.46/nsis-2.46-setup.exe" -FileName nsissetup.exe
  - nsissetup /S /D=%NSIS_ROOT%

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  # Fixed tag version number if using a tag.
  - cmd: if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  # vcbuild overwrites the platform variable.
  - cmd: set ARCH=%platform%
  - cmd: vcbuild.bat release shared %ARCH%

after_build:
  - '%NSIS_ROOT%\makensis /DVERSION=%APPVEYOR_BUILD_VERSION% /DARCH=%ARCH% libuv.nsi'

artifacts:
  - name: Installer
    path: 'libuv-*.exe'

deploy:
  # Deploy to github on new tag
  - provider: GitHub
    artifact: Installer
    draft: false
    prerelease: false
    auth_token:
      secure: replace-with-encrypted-github-token
    on:
      appveyor_repo_tag: true # deploy on tag push only

cache:
  - C:\projects\libuv\build\gyp
